// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_LAYERNORMATTRIBUTES_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_LAYERNORMATTRIBUTES_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "norm_common_generated.h"

namespace hipdnn_flatbuffers_sdk {
namespace data_objects {

struct LayernormAttributes;
struct LayernormAttributesBuilder;
struct LayernormAttributesT;

bool operator==(const LayernormAttributesT &lhs, const LayernormAttributesT &rhs);
bool operator!=(const LayernormAttributesT &lhs, const LayernormAttributesT &rhs);

struct LayernormAttributesT : public ::flatbuffers::NativeTable {
  typedef LayernormAttributes TableType;
  int64_t x_tensor_uid = 0;
  int64_t scale_tensor_uid = 0;
  int64_t bias_tensor_uid = 0;
  int64_t epsilon_tensor_uid = 0;
  int64_t y_tensor_uid = 0;
  int64_t normalized_dim_count = 0;
  ::flatbuffers::Optional<int64_t> mean_tensor_uid = ::flatbuffers::nullopt;
  ::flatbuffers::Optional<int64_t> inv_variance_tensor_uid = ::flatbuffers::nullopt;
  hipdnn_flatbuffers_sdk::data_objects::NormFwdPhase forward_phase = hipdnn_flatbuffers_sdk::data_objects::NormFwdPhase::NOT_SET;
};

struct LayernormAttributes FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LayernormAttributesT NativeTableType;
  typedef LayernormAttributesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X_TENSOR_UID = 4,
    VT_SCALE_TENSOR_UID = 6,
    VT_BIAS_TENSOR_UID = 8,
    VT_EPSILON_TENSOR_UID = 10,
    VT_Y_TENSOR_UID = 12,
    VT_NORMALIZED_DIM_COUNT = 14,
    VT_MEAN_TENSOR_UID = 16,
    VT_INV_VARIANCE_TENSOR_UID = 18,
    VT_FORWARD_PHASE = 20
  };
  int64_t x_tensor_uid() const {
    return GetField<int64_t>(VT_X_TENSOR_UID, 0);
  }
  bool mutate_x_tensor_uid(int64_t _x_tensor_uid = 0) {
    return SetField<int64_t>(VT_X_TENSOR_UID, _x_tensor_uid, 0);
  }
  int64_t scale_tensor_uid() const {
    return GetField<int64_t>(VT_SCALE_TENSOR_UID, 0);
  }
  bool mutate_scale_tensor_uid(int64_t _scale_tensor_uid = 0) {
    return SetField<int64_t>(VT_SCALE_TENSOR_UID, _scale_tensor_uid, 0);
  }
  int64_t bias_tensor_uid() const {
    return GetField<int64_t>(VT_BIAS_TENSOR_UID, 0);
  }
  bool mutate_bias_tensor_uid(int64_t _bias_tensor_uid = 0) {
    return SetField<int64_t>(VT_BIAS_TENSOR_UID, _bias_tensor_uid, 0);
  }
  int64_t epsilon_tensor_uid() const {
    return GetField<int64_t>(VT_EPSILON_TENSOR_UID, 0);
  }
  bool mutate_epsilon_tensor_uid(int64_t _epsilon_tensor_uid = 0) {
    return SetField<int64_t>(VT_EPSILON_TENSOR_UID, _epsilon_tensor_uid, 0);
  }
  int64_t y_tensor_uid() const {
    return GetField<int64_t>(VT_Y_TENSOR_UID, 0);
  }
  bool mutate_y_tensor_uid(int64_t _y_tensor_uid = 0) {
    return SetField<int64_t>(VT_Y_TENSOR_UID, _y_tensor_uid, 0);
  }
  int64_t normalized_dim_count() const {
    return GetField<int64_t>(VT_NORMALIZED_DIM_COUNT, 0);
  }
  bool mutate_normalized_dim_count(int64_t _normalized_dim_count = 0) {
    return SetField<int64_t>(VT_NORMALIZED_DIM_COUNT, _normalized_dim_count, 0);
  }
  ::flatbuffers::Optional<int64_t> mean_tensor_uid() const {
    return GetOptional<int64_t, int64_t>(VT_MEAN_TENSOR_UID);
  }
  bool mutate_mean_tensor_uid(int64_t _mean_tensor_uid) {
    return SetField<int64_t>(VT_MEAN_TENSOR_UID, _mean_tensor_uid);
  }
  ::flatbuffers::Optional<int64_t> inv_variance_tensor_uid() const {
    return GetOptional<int64_t, int64_t>(VT_INV_VARIANCE_TENSOR_UID);
  }
  bool mutate_inv_variance_tensor_uid(int64_t _inv_variance_tensor_uid) {
    return SetField<int64_t>(VT_INV_VARIANCE_TENSOR_UID, _inv_variance_tensor_uid);
  }
  hipdnn_flatbuffers_sdk::data_objects::NormFwdPhase forward_phase() const {
    return static_cast<hipdnn_flatbuffers_sdk::data_objects::NormFwdPhase>(GetField<int8_t>(VT_FORWARD_PHASE, 0));
  }
  bool mutate_forward_phase(hipdnn_flatbuffers_sdk::data_objects::NormFwdPhase _forward_phase = static_cast<hipdnn_flatbuffers_sdk::data_objects::NormFwdPhase>(0)) {
    return SetField<int8_t>(VT_FORWARD_PHASE, static_cast<int8_t>(_forward_phase), 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_X_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_SCALE_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_BIAS_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_EPSILON_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_Y_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_NORMALIZED_DIM_COUNT, 8) &&
           VerifyField<int64_t>(verifier, VT_MEAN_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_INV_VARIANCE_TENSOR_UID, 8) &&
           VerifyField<int8_t>(verifier, VT_FORWARD_PHASE, 1) &&
           verifier.EndTable();
  }
  LayernormAttributesT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(LayernormAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<LayernormAttributes> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const LayernormAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct LayernormAttributesBuilder {
  typedef LayernormAttributes Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x_tensor_uid(int64_t x_tensor_uid) {
    fbb_.AddElement<int64_t>(LayernormAttributes::VT_X_TENSOR_UID, x_tensor_uid, 0);
  }
  void add_scale_tensor_uid(int64_t scale_tensor_uid) {
    fbb_.AddElement<int64_t>(LayernormAttributes::VT_SCALE_TENSOR_UID, scale_tensor_uid, 0);
  }
  void add_bias_tensor_uid(int64_t bias_tensor_uid) {
    fbb_.AddElement<int64_t>(LayernormAttributes::VT_BIAS_TENSOR_UID, bias_tensor_uid, 0);
  }
  void add_epsilon_tensor_uid(int64_t epsilon_tensor_uid) {
    fbb_.AddElement<int64_t>(LayernormAttributes::VT_EPSILON_TENSOR_UID, epsilon_tensor_uid, 0);
  }
  void add_y_tensor_uid(int64_t y_tensor_uid) {
    fbb_.AddElement<int64_t>(LayernormAttributes::VT_Y_TENSOR_UID, y_tensor_uid, 0);
  }
  void add_normalized_dim_count(int64_t normalized_dim_count) {
    fbb_.AddElement<int64_t>(LayernormAttributes::VT_NORMALIZED_DIM_COUNT, normalized_dim_count, 0);
  }
  void add_mean_tensor_uid(int64_t mean_tensor_uid) {
    fbb_.AddElement<int64_t>(LayernormAttributes::VT_MEAN_TENSOR_UID, mean_tensor_uid);
  }
  void add_inv_variance_tensor_uid(int64_t inv_variance_tensor_uid) {
    fbb_.AddElement<int64_t>(LayernormAttributes::VT_INV_VARIANCE_TENSOR_UID, inv_variance_tensor_uid);
  }
  void add_forward_phase(hipdnn_flatbuffers_sdk::data_objects::NormFwdPhase forward_phase) {
    fbb_.AddElement<int8_t>(LayernormAttributes::VT_FORWARD_PHASE, static_cast<int8_t>(forward_phase), 0);
  }
  explicit LayernormAttributesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LayernormAttributes> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LayernormAttributes>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LayernormAttributes> CreateLayernormAttributes(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t x_tensor_uid = 0,
    int64_t scale_tensor_uid = 0,
    int64_t bias_tensor_uid = 0,
    int64_t epsilon_tensor_uid = 0,
    int64_t y_tensor_uid = 0,
    int64_t normalized_dim_count = 0,
    ::flatbuffers::Optional<int64_t> mean_tensor_uid = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<int64_t> inv_variance_tensor_uid = ::flatbuffers::nullopt,
    hipdnn_flatbuffers_sdk::data_objects::NormFwdPhase forward_phase = hipdnn_flatbuffers_sdk::data_objects::NormFwdPhase::NOT_SET) {
  LayernormAttributesBuilder builder_(_fbb);
  if(inv_variance_tensor_uid) { builder_.add_inv_variance_tensor_uid(*inv_variance_tensor_uid); }
  if(mean_tensor_uid) { builder_.add_mean_tensor_uid(*mean_tensor_uid); }
  builder_.add_normalized_dim_count(normalized_dim_count);
  builder_.add_y_tensor_uid(y_tensor_uid);
  builder_.add_epsilon_tensor_uid(epsilon_tensor_uid);
  builder_.add_bias_tensor_uid(bias_tensor_uid);
  builder_.add_scale_tensor_uid(scale_tensor_uid);
  builder_.add_x_tensor_uid(x_tensor_uid);
  builder_.add_forward_phase(forward_phase);
  return builder_.Finish();
}

::flatbuffers::Offset<LayernormAttributes> CreateLayernormAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const LayernormAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const LayernormAttributesT &lhs, const LayernormAttributesT &rhs) {
  return
      (lhs.x_tensor_uid == rhs.x_tensor_uid) &&
      (lhs.scale_tensor_uid == rhs.scale_tensor_uid) &&
      (lhs.bias_tensor_uid == rhs.bias_tensor_uid) &&
      (lhs.epsilon_tensor_uid == rhs.epsilon_tensor_uid) &&
      (lhs.y_tensor_uid == rhs.y_tensor_uid) &&
      (lhs.normalized_dim_count == rhs.normalized_dim_count) &&
      (lhs.mean_tensor_uid == rhs.mean_tensor_uid) &&
      (lhs.inv_variance_tensor_uid == rhs.inv_variance_tensor_uid) &&
      (lhs.forward_phase == rhs.forward_phase);
}

inline bool operator!=(const LayernormAttributesT &lhs, const LayernormAttributesT &rhs) {
    return !(lhs == rhs);
}


inline LayernormAttributesT *LayernormAttributes::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<LayernormAttributesT>(new LayernormAttributesT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void LayernormAttributes::UnPackTo(LayernormAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x_tensor_uid(); _o->x_tensor_uid = _e; }
  { auto _e = scale_tensor_uid(); _o->scale_tensor_uid = _e; }
  { auto _e = bias_tensor_uid(); _o->bias_tensor_uid = _e; }
  { auto _e = epsilon_tensor_uid(); _o->epsilon_tensor_uid = _e; }
  { auto _e = y_tensor_uid(); _o->y_tensor_uid = _e; }
  { auto _e = normalized_dim_count(); _o->normalized_dim_count = _e; }
  { auto _e = mean_tensor_uid(); _o->mean_tensor_uid = _e; }
  { auto _e = inv_variance_tensor_uid(); _o->inv_variance_tensor_uid = _e; }
  { auto _e = forward_phase(); _o->forward_phase = _e; }
}

inline ::flatbuffers::Offset<LayernormAttributes> LayernormAttributes::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const LayernormAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateLayernormAttributes(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<LayernormAttributes> CreateLayernormAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const LayernormAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const LayernormAttributesT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x_tensor_uid = _o->x_tensor_uid;
  auto _scale_tensor_uid = _o->scale_tensor_uid;
  auto _bias_tensor_uid = _o->bias_tensor_uid;
  auto _epsilon_tensor_uid = _o->epsilon_tensor_uid;
  auto _y_tensor_uid = _o->y_tensor_uid;
  auto _normalized_dim_count = _o->normalized_dim_count;
  auto _mean_tensor_uid = _o->mean_tensor_uid;
  auto _inv_variance_tensor_uid = _o->inv_variance_tensor_uid;
  auto _forward_phase = _o->forward_phase;
  return hipdnn_flatbuffers_sdk::data_objects::CreateLayernormAttributes(
      _fbb,
      _x_tensor_uid,
      _scale_tensor_uid,
      _bias_tensor_uid,
      _epsilon_tensor_uid,
      _y_tensor_uid,
      _normalized_dim_count,
      _mean_tensor_uid,
      _inv_variance_tensor_uid,
      _forward_phase);
}

}  // namespace data_objects
}  // namespace hipdnn_flatbuffers_sdk

#endif  // FLATBUFFERS_GENERATED_LAYERNORMATTRIBUTES_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_
