// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_NORMCOMMON_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_NORMCOMMON_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");


namespace hipdnn_flatbuffers_sdk {
namespace data_objects {

enum class NormFwdPhase : int8_t {
  NOT_SET = 0,
  INFERENCE = 1,
  TRAINING = 2,
  MIN = NOT_SET,
  MAX = TRAINING
};

inline const NormFwdPhase (&EnumValuesNormFwdPhase())[3] {
  static const NormFwdPhase values[] = {
    NormFwdPhase::NOT_SET,
    NormFwdPhase::INFERENCE,
    NormFwdPhase::TRAINING
  };
  return values;
}

inline const char * const *EnumNamesNormFwdPhase() {
  static const char * const names[4] = {
    "NOT_SET",
    "INFERENCE",
    "TRAINING",
    nullptr
  };
  return names;
}

inline const char *EnumNameNormFwdPhase(NormFwdPhase e) {
  if (::flatbuffers::IsOutRange(e, NormFwdPhase::NOT_SET, NormFwdPhase::TRAINING)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesNormFwdPhase()[index];
}

}  // namespace data_objects
}  // namespace hipdnn_flatbuffers_sdk

#endif  // FLATBUFFERS_GENERATED_NORMCOMMON_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_
