// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RESAMPLECOMMON_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_RESAMPLECOMMON_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");


namespace hipdnn_flatbuffers_sdk {
namespace data_objects {

enum class ResampleMode : int8_t {
  NOT_SET = 0,
  MAXPOOL = 1,
  AVGPOOL_EXCLUDE_PADDING = 2,
  AVGPOOL_INCLUDE_PADDING = 3,
  MIN = NOT_SET,
  MAX = AVGPOOL_INCLUDE_PADDING
};

inline const ResampleMode (&EnumValuesResampleMode())[4] {
  static const ResampleMode values[] = {
    ResampleMode::NOT_SET,
    ResampleMode::MAXPOOL,
    ResampleMode::AVGPOOL_EXCLUDE_PADDING,
    ResampleMode::AVGPOOL_INCLUDE_PADDING
  };
  return values;
}

inline const char * const *EnumNamesResampleMode() {
  static const char * const names[5] = {
    "NOT_SET",
    "MAXPOOL",
    "AVGPOOL_EXCLUDE_PADDING",
    "AVGPOOL_INCLUDE_PADDING",
    nullptr
  };
  return names;
}

inline const char *EnumNameResampleMode(ResampleMode e) {
  if (::flatbuffers::IsOutRange(e, ResampleMode::NOT_SET, ResampleMode::AVGPOOL_INCLUDE_PADDING)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesResampleMode()[index];
}

enum class PaddingMode : int8_t {
  PADDING_NOT_SET = 0,
  NEG_INF_PAD = 1,
  ZERO_PAD = 2,
  MIN = PADDING_NOT_SET,
  MAX = ZERO_PAD
};

inline const PaddingMode (&EnumValuesPaddingMode())[3] {
  static const PaddingMode values[] = {
    PaddingMode::PADDING_NOT_SET,
    PaddingMode::NEG_INF_PAD,
    PaddingMode::ZERO_PAD
  };
  return values;
}

inline const char * const *EnumNamesPaddingMode() {
  static const char * const names[4] = {
    "PADDING_NOT_SET",
    "NEG_INF_PAD",
    "ZERO_PAD",
    nullptr
  };
  return names;
}

inline const char *EnumNamePaddingMode(PaddingMode e) {
  if (::flatbuffers::IsOutRange(e, PaddingMode::PADDING_NOT_SET, PaddingMode::ZERO_PAD)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPaddingMode()[index];
}

}  // namespace data_objects
}  // namespace hipdnn_flatbuffers_sdk

#endif  // FLATBUFFERS_GENERATED_RESAMPLECOMMON_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_
