// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RESAMPLEFWDATTRIBUTES_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_RESAMPLEFWDATTRIBUTES_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "resample_common_generated.h"

namespace hipdnn_flatbuffers_sdk {
namespace data_objects {

struct ResampleFwdAttributes;
struct ResampleFwdAttributesBuilder;
struct ResampleFwdAttributesT;

bool operator==(const ResampleFwdAttributesT &lhs, const ResampleFwdAttributesT &rhs);
bool operator!=(const ResampleFwdAttributesT &lhs, const ResampleFwdAttributesT &rhs);

struct ResampleFwdAttributesT : public ::flatbuffers::NativeTable {
  typedef ResampleFwdAttributes TableType;
  int64_t x_tensor_uid = 0;
  int64_t y_tensor_uid = 0;
  ::flatbuffers::Optional<int64_t> index_tensor_uid = ::flatbuffers::nullopt;
  std::vector<int64_t> pre_padding{};
  std::vector<int64_t> post_padding{};
  std::vector<int64_t> stride{};
  std::vector<int64_t> window{};
  hipdnn_flatbuffers_sdk::data_objects::ResampleMode resample_mode = hipdnn_flatbuffers_sdk::data_objects::ResampleMode::NOT_SET;
  hipdnn_flatbuffers_sdk::data_objects::PaddingMode padding_mode = hipdnn_flatbuffers_sdk::data_objects::PaddingMode::PADDING_NOT_SET;
  ::flatbuffers::Optional<bool> generate_index = ::flatbuffers::nullopt;
};

struct ResampleFwdAttributes FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ResampleFwdAttributesT NativeTableType;
  typedef ResampleFwdAttributesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X_TENSOR_UID = 4,
    VT_Y_TENSOR_UID = 6,
    VT_INDEX_TENSOR_UID = 8,
    VT_PRE_PADDING = 10,
    VT_POST_PADDING = 12,
    VT_STRIDE = 14,
    VT_WINDOW = 16,
    VT_RESAMPLE_MODE = 18,
    VT_PADDING_MODE = 20,
    VT_GENERATE_INDEX = 22
  };
  int64_t x_tensor_uid() const {
    return GetField<int64_t>(VT_X_TENSOR_UID, 0);
  }
  bool mutate_x_tensor_uid(int64_t _x_tensor_uid = 0) {
    return SetField<int64_t>(VT_X_TENSOR_UID, _x_tensor_uid, 0);
  }
  int64_t y_tensor_uid() const {
    return GetField<int64_t>(VT_Y_TENSOR_UID, 0);
  }
  bool mutate_y_tensor_uid(int64_t _y_tensor_uid = 0) {
    return SetField<int64_t>(VT_Y_TENSOR_UID, _y_tensor_uid, 0);
  }
  ::flatbuffers::Optional<int64_t> index_tensor_uid() const {
    return GetOptional<int64_t, int64_t>(VT_INDEX_TENSOR_UID);
  }
  bool mutate_index_tensor_uid(int64_t _index_tensor_uid) {
    return SetField<int64_t>(VT_INDEX_TENSOR_UID, _index_tensor_uid);
  }
  const ::flatbuffers::Vector<int64_t> *pre_padding() const {
    return GetPointer<const ::flatbuffers::Vector<int64_t> *>(VT_PRE_PADDING);
  }
  ::flatbuffers::Vector<int64_t> *mutable_pre_padding() {
    return GetPointer<::flatbuffers::Vector<int64_t> *>(VT_PRE_PADDING);
  }
  const ::flatbuffers::Vector<int64_t> *post_padding() const {
    return GetPointer<const ::flatbuffers::Vector<int64_t> *>(VT_POST_PADDING);
  }
  ::flatbuffers::Vector<int64_t> *mutable_post_padding() {
    return GetPointer<::flatbuffers::Vector<int64_t> *>(VT_POST_PADDING);
  }
  const ::flatbuffers::Vector<int64_t> *stride() const {
    return GetPointer<const ::flatbuffers::Vector<int64_t> *>(VT_STRIDE);
  }
  ::flatbuffers::Vector<int64_t> *mutable_stride() {
    return GetPointer<::flatbuffers::Vector<int64_t> *>(VT_STRIDE);
  }
  const ::flatbuffers::Vector<int64_t> *window() const {
    return GetPointer<const ::flatbuffers::Vector<int64_t> *>(VT_WINDOW);
  }
  ::flatbuffers::Vector<int64_t> *mutable_window() {
    return GetPointer<::flatbuffers::Vector<int64_t> *>(VT_WINDOW);
  }
  hipdnn_flatbuffers_sdk::data_objects::ResampleMode resample_mode() const {
    return static_cast<hipdnn_flatbuffers_sdk::data_objects::ResampleMode>(GetField<int8_t>(VT_RESAMPLE_MODE, 0));
  }
  bool mutate_resample_mode(hipdnn_flatbuffers_sdk::data_objects::ResampleMode _resample_mode = static_cast<hipdnn_flatbuffers_sdk::data_objects::ResampleMode>(0)) {
    return SetField<int8_t>(VT_RESAMPLE_MODE, static_cast<int8_t>(_resample_mode), 0);
  }
  hipdnn_flatbuffers_sdk::data_objects::PaddingMode padding_mode() const {
    return static_cast<hipdnn_flatbuffers_sdk::data_objects::PaddingMode>(GetField<int8_t>(VT_PADDING_MODE, 0));
  }
  bool mutate_padding_mode(hipdnn_flatbuffers_sdk::data_objects::PaddingMode _padding_mode = static_cast<hipdnn_flatbuffers_sdk::data_objects::PaddingMode>(0)) {
    return SetField<int8_t>(VT_PADDING_MODE, static_cast<int8_t>(_padding_mode), 0);
  }
  ::flatbuffers::Optional<bool> generate_index() const {
    return GetOptional<uint8_t, bool>(VT_GENERATE_INDEX);
  }
  bool mutate_generate_index(bool _generate_index) {
    return SetField<uint8_t>(VT_GENERATE_INDEX, static_cast<uint8_t>(_generate_index));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_X_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_Y_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_INDEX_TENSOR_UID, 8) &&
           VerifyOffset(verifier, VT_PRE_PADDING) &&
           verifier.VerifyVector(pre_padding()) &&
           VerifyOffset(verifier, VT_POST_PADDING) &&
           verifier.VerifyVector(post_padding()) &&
           VerifyOffset(verifier, VT_STRIDE) &&
           verifier.VerifyVector(stride()) &&
           VerifyOffset(verifier, VT_WINDOW) &&
           verifier.VerifyVector(window()) &&
           VerifyField<int8_t>(verifier, VT_RESAMPLE_MODE, 1) &&
           VerifyField<int8_t>(verifier, VT_PADDING_MODE, 1) &&
           VerifyField<uint8_t>(verifier, VT_GENERATE_INDEX, 1) &&
           verifier.EndTable();
  }
  ResampleFwdAttributesT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ResampleFwdAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ResampleFwdAttributes> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ResampleFwdAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ResampleFwdAttributesBuilder {
  typedef ResampleFwdAttributes Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x_tensor_uid(int64_t x_tensor_uid) {
    fbb_.AddElement<int64_t>(ResampleFwdAttributes::VT_X_TENSOR_UID, x_tensor_uid, 0);
  }
  void add_y_tensor_uid(int64_t y_tensor_uid) {
    fbb_.AddElement<int64_t>(ResampleFwdAttributes::VT_Y_TENSOR_UID, y_tensor_uid, 0);
  }
  void add_index_tensor_uid(int64_t index_tensor_uid) {
    fbb_.AddElement<int64_t>(ResampleFwdAttributes::VT_INDEX_TENSOR_UID, index_tensor_uid);
  }
  void add_pre_padding(::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> pre_padding) {
    fbb_.AddOffset(ResampleFwdAttributes::VT_PRE_PADDING, pre_padding);
  }
  void add_post_padding(::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> post_padding) {
    fbb_.AddOffset(ResampleFwdAttributes::VT_POST_PADDING, post_padding);
  }
  void add_stride(::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> stride) {
    fbb_.AddOffset(ResampleFwdAttributes::VT_STRIDE, stride);
  }
  void add_window(::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> window) {
    fbb_.AddOffset(ResampleFwdAttributes::VT_WINDOW, window);
  }
  void add_resample_mode(hipdnn_flatbuffers_sdk::data_objects::ResampleMode resample_mode) {
    fbb_.AddElement<int8_t>(ResampleFwdAttributes::VT_RESAMPLE_MODE, static_cast<int8_t>(resample_mode), 0);
  }
  void add_padding_mode(hipdnn_flatbuffers_sdk::data_objects::PaddingMode padding_mode) {
    fbb_.AddElement<int8_t>(ResampleFwdAttributes::VT_PADDING_MODE, static_cast<int8_t>(padding_mode), 0);
  }
  void add_generate_index(bool generate_index) {
    fbb_.AddElement<uint8_t>(ResampleFwdAttributes::VT_GENERATE_INDEX, static_cast<uint8_t>(generate_index));
  }
  explicit ResampleFwdAttributesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ResampleFwdAttributes> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ResampleFwdAttributes>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ResampleFwdAttributes> CreateResampleFwdAttributes(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t x_tensor_uid = 0,
    int64_t y_tensor_uid = 0,
    ::flatbuffers::Optional<int64_t> index_tensor_uid = ::flatbuffers::nullopt,
    ::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> pre_padding = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> post_padding = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> stride = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> window = 0,
    hipdnn_flatbuffers_sdk::data_objects::ResampleMode resample_mode = hipdnn_flatbuffers_sdk::data_objects::ResampleMode::NOT_SET,
    hipdnn_flatbuffers_sdk::data_objects::PaddingMode padding_mode = hipdnn_flatbuffers_sdk::data_objects::PaddingMode::PADDING_NOT_SET,
    ::flatbuffers::Optional<bool> generate_index = ::flatbuffers::nullopt) {
  ResampleFwdAttributesBuilder builder_(_fbb);
  if(index_tensor_uid) { builder_.add_index_tensor_uid(*index_tensor_uid); }
  builder_.add_y_tensor_uid(y_tensor_uid);
  builder_.add_x_tensor_uid(x_tensor_uid);
  builder_.add_window(window);
  builder_.add_stride(stride);
  builder_.add_post_padding(post_padding);
  builder_.add_pre_padding(pre_padding);
  if(generate_index) { builder_.add_generate_index(*generate_index); }
  builder_.add_padding_mode(padding_mode);
  builder_.add_resample_mode(resample_mode);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ResampleFwdAttributes> CreateResampleFwdAttributesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t x_tensor_uid = 0,
    int64_t y_tensor_uid = 0,
    ::flatbuffers::Optional<int64_t> index_tensor_uid = ::flatbuffers::nullopt,
    const std::vector<int64_t> *pre_padding = nullptr,
    const std::vector<int64_t> *post_padding = nullptr,
    const std::vector<int64_t> *stride = nullptr,
    const std::vector<int64_t> *window = nullptr,
    hipdnn_flatbuffers_sdk::data_objects::ResampleMode resample_mode = hipdnn_flatbuffers_sdk::data_objects::ResampleMode::NOT_SET,
    hipdnn_flatbuffers_sdk::data_objects::PaddingMode padding_mode = hipdnn_flatbuffers_sdk::data_objects::PaddingMode::PADDING_NOT_SET,
    ::flatbuffers::Optional<bool> generate_index = ::flatbuffers::nullopt) {
  auto pre_padding__ = pre_padding ? _fbb.CreateVector<int64_t>(*pre_padding) : 0;
  auto post_padding__ = post_padding ? _fbb.CreateVector<int64_t>(*post_padding) : 0;
  auto stride__ = stride ? _fbb.CreateVector<int64_t>(*stride) : 0;
  auto window__ = window ? _fbb.CreateVector<int64_t>(*window) : 0;
  return hipdnn_flatbuffers_sdk::data_objects::CreateResampleFwdAttributes(
      _fbb,
      x_tensor_uid,
      y_tensor_uid,
      index_tensor_uid,
      pre_padding__,
      post_padding__,
      stride__,
      window__,
      resample_mode,
      padding_mode,
      generate_index);
}

::flatbuffers::Offset<ResampleFwdAttributes> CreateResampleFwdAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const ResampleFwdAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const ResampleFwdAttributesT &lhs, const ResampleFwdAttributesT &rhs) {
  return
      (lhs.x_tensor_uid == rhs.x_tensor_uid) &&
      (lhs.y_tensor_uid == rhs.y_tensor_uid) &&
      (lhs.index_tensor_uid == rhs.index_tensor_uid) &&
      (lhs.pre_padding == rhs.pre_padding) &&
      (lhs.post_padding == rhs.post_padding) &&
      (lhs.stride == rhs.stride) &&
      (lhs.window == rhs.window) &&
      (lhs.resample_mode == rhs.resample_mode) &&
      (lhs.padding_mode == rhs.padding_mode) &&
      (lhs.generate_index == rhs.generate_index);
}

inline bool operator!=(const ResampleFwdAttributesT &lhs, const ResampleFwdAttributesT &rhs) {
    return !(lhs == rhs);
}


inline ResampleFwdAttributesT *ResampleFwdAttributes::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ResampleFwdAttributesT>(new ResampleFwdAttributesT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ResampleFwdAttributes::UnPackTo(ResampleFwdAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x_tensor_uid(); _o->x_tensor_uid = _e; }
  { auto _e = y_tensor_uid(); _o->y_tensor_uid = _e; }
  { auto _e = index_tensor_uid(); _o->index_tensor_uid = _e; }
  { auto _e = pre_padding(); if (_e) { _o->pre_padding.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->pre_padding[_i] = _e->Get(_i); } } else { _o->pre_padding.resize(0); } }
  { auto _e = post_padding(); if (_e) { _o->post_padding.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->post_padding[_i] = _e->Get(_i); } } else { _o->post_padding.resize(0); } }
  { auto _e = stride(); if (_e) { _o->stride.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->stride[_i] = _e->Get(_i); } } else { _o->stride.resize(0); } }
  { auto _e = window(); if (_e) { _o->window.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->window[_i] = _e->Get(_i); } } else { _o->window.resize(0); } }
  { auto _e = resample_mode(); _o->resample_mode = _e; }
  { auto _e = padding_mode(); _o->padding_mode = _e; }
  { auto _e = generate_index(); _o->generate_index = _e; }
}

inline ::flatbuffers::Offset<ResampleFwdAttributes> ResampleFwdAttributes::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ResampleFwdAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateResampleFwdAttributes(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ResampleFwdAttributes> CreateResampleFwdAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const ResampleFwdAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ResampleFwdAttributesT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x_tensor_uid = _o->x_tensor_uid;
  auto _y_tensor_uid = _o->y_tensor_uid;
  auto _index_tensor_uid = _o->index_tensor_uid;
  auto _pre_padding = _o->pre_padding.size() ? _fbb.CreateVector(_o->pre_padding) : 0;
  auto _post_padding = _o->post_padding.size() ? _fbb.CreateVector(_o->post_padding) : 0;
  auto _stride = _o->stride.size() ? _fbb.CreateVector(_o->stride) : 0;
  auto _window = _o->window.size() ? _fbb.CreateVector(_o->window) : 0;
  auto _resample_mode = _o->resample_mode;
  auto _padding_mode = _o->padding_mode;
  auto _generate_index = _o->generate_index;
  return hipdnn_flatbuffers_sdk::data_objects::CreateResampleFwdAttributes(
      _fbb,
      _x_tensor_uid,
      _y_tensor_uid,
      _index_tensor_uid,
      _pre_padding,
      _post_padding,
      _stride,
      _window,
      _resample_mode,
      _padding_mode,
      _generate_index);
}

}  // namespace data_objects
}  // namespace hipdnn_flatbuffers_sdk

#endif  // FLATBUFFERS_GENERATED_RESAMPLEFWDATTRIBUTES_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_
