#!/bin/bash -x

# Copyright Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

# Runs all the CodeQL queries in rr-checks, saving results to codeql.sarif .

# Installing the SARIF VSCode extension will display issues in a nice viewer format
# Alternatively: --format=csv

# export PATH=$PATH:/opt/codeql/codeql

codeql database analyze codeql/build/rr-database codeql/cpp/src/rr-query-suites.qls \
    --format=sarifv2.1.0 --output=codeql/build/codeql.sarif \
    --search-path=codeql/build/codeql-cli:codeql/cpp \
    -j$(nproc) --rerun \
    --compilation-cache=codeql/build/.cache/ \
    --no-default-compilation-cache

./codeql/filter_sarif.py \
  codeql/build/codeql.sarif \
  codeql/exclude_paths.txt \
  -o codeql/build/codeql.sarif.filtered

sarif csv --output codeql/build/codeql.csv codeql/build/codeql.sarif.filtered

./codeql/csv_to_html.py
