#!/usr/bin/env python3
################################################################################
#
# MIT License
#
# Copyright 2025 AMD ROCm(TM) Software
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell cop-
# ies of the Software, and to permit persons to whom the Software is furnished
# to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IM-
# PLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNE-
# CTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
################################################################################

"""
Sorts a list of paths by directory and then by filename. Useful for sorting the
file paths in CMake files.
"""

# import pathlib
import collections
import os.path
import sys

if __name__ == "__main__":
    for arg in sys.argv[1:]:
        if "help" in arg or "-h in arg":
            print(__doc__)
            exit()

    dirs = collections.defaultdict(list)

    for line in sorted(sys.stdin):
        if line.strip() != "":
            path, name = os.path.split(line)
            dirs[path].append(name)

    first = True
    for path in sorted(dirs.keys()):
        if not first:
            print()

        for name in sorted(set(dirs[path])):
            print(os.path.join(path, name), end="")

        first = False
