#!/bin/bash

# Copyright Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

# This pre-commit hook checks if any versions of clang-format
# are installed, and if so, uses the installed version to format
# the staged changes.

export PATH=/opt/clang-format/bin:/usr/bin:/bin::/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin

# Redirect stdout to stderr.
exec >&2

# Do everything from top - level
cd $(git rev-parse --show-toplevel)

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

if [[ "$1" == "--reformat" ]]; then
    files=$(git ls-files --exclude-standard -- shared/rocroller/)
else
    files=$(git diff-index --cached --name-only $against -- shared/rocroller/)
fi

[[ -z "$files" ]] && exit

# do the formatting
for file in $files; do
    if [[ -e $file ]] && echo $file | grep -Eq '\.c$|\.h$|\.hpp$|\.cpp$|\.cl$|\.in$|\.txt$|\.yaml$|\.yml$|\.sh$|\.py$|\.pl$|\.cmake$|\.md$|\.rst$|\.groovy$|\.ini$|\.awk$|\.csv$'; then
        echo "Processing line endings in $file"
        sed -i -e 's/[[:space:]]*$//' "$file" # Remove whitespace at end of lines
        sed -i -e '$a\' "$file" # Add missing newline to end of file

        if grep -q $'\t' "$file"; then # Replace tabs with spaces.
            echo "Removing tabs in $file"
            tmpfile=$(mktemp /tmp/githook.XXXXXX)
            expand -t 4 "${file}" > "${tmpfile}"
            cat "${tmpfile}" > "${file}"
            rm -rf "${tmpfile}"
        fi

        echo "Converting non-ASCII characters to ASCII equivalents in $file"
        # Convert UTF8 non-ASCII to ASCII
        temp=$(mktemp)
        [[ -w $temp ]] || exit
        iconv -s -f utf-8 -t ascii//TRANSLIT "$file" > "$temp" || exit
        chmod --reference="$file" "$temp" || exit
        mv -f "$temp" "$file" || exit
        git add -u "$file"
    fi
done

# if clang-format exists, run it on C/C++ files
if command -v clang-format >/dev/null; then
    for file in $files; do
       if [[ -e $file ]] && echo $file | grep -Eq '\.c$|\.h$|\.hpp$|\.cpp$|\.cl$|\.h\.in$|\.hpp\.in$|\.cpp\.in$'; then
            echo "clang-format $file"
            clang-format -i -style=file "$file"
            git add -u "$file"
        fi
    done
fi

# if black(python formatter) exists, run it on python files
if command -v black >/dev/null; then
    for file in $files; do
       if [[ -e $file ]] && ( echo $file | grep -Eq '\.py$' ||  grep -q "^#!.*python" "$file" ) ; then
            echo "black $file"
            black "$file"
            git add -u "$file"
        fi
    done
fi
